In [1]:
import numpy as np


# decending selection 

In [8]:

def selectionSort(array, size):
	
	for ind in range(size):
		min_index = ind

		for j in range(ind + 1, size):
			if array[j] < array[min_index]:
				min_index = j
		(array[ind], array[min_index]) = (array[min_index], array[ind])

arr = np.arange(10000)

array=np.flip(arr)
print(array)
size = len(array)
selectionSort(array, size)
print('The array after sorting in Ascending Order by selection sort is:')
print(array)


[9999 9998 9997 ...    2    1    0]
The array after sorting in Ascending Order by selection sort is:
[   0    1    2 ... 9997 9998 9999]


# accending sort

In [6]:

def selectionSort(array, size):
	
	for ind in range(size):
		min_index = ind

		for j in range(ind + 1, size):
			if array[j] < array[min_index]:
				min_index = j
		(array[ind], array[min_index]) = (array[min_index], array[ind])

array = np.arange(10000)
print(array)
#array=np.flip(arr)
size = len(array)
selectionSort(array, size)
print('The array after sorting in Ascending Order by selection sort is:')
print(array)


[   0    1    2 ... 9997 9998 9999]
The array after sorting in Ascending Order by selection sort is:
[   0    1    2 ... 9997 9998 9999]


# randoom

In [9]:

def selectionSort(array, size):
	
	for ind in range(size):
		min_index = ind

		for j in range(ind + 1, size):
			if array[j] < array[min_index]:
				min_index = j
		(array[ind], array[min_index]) = (array[min_index], array[ind])

array = np.arange(10000)
np.random.shuffle(array)
print(array)
#array=np.flip(arr)
size = len(array)
selectionSort(array, size)
print('The array after sorting in Ascending Order by selection sort is:')
print(array)


[6253  104 5579 ... 2507 7054  959]
The array after sorting in Ascending Order by selection sort is:
[   0    1    2 ... 9997 9998 9999]
